export const CARDS: card[] = [
  {
    id: 1,
    value: 1,
    suit: 'Ouros',
    name: '1 de Ouross',
    rule: 'Distribua 1 shot!',
    imgURL: require('../../assets/cards/ace_of_diamonds.png'),
  },
  {
    id: 2,
    value: 1,
    suit: 'Espadas',
    name: '1 de Espadas',
    rule: 'Distribua 1 shot!',
    imgURL: require('../../assets/cards/ace_of_spades.png'),
  },
  {
    id: 3,
    value: 1,
    suit: 'Paus',
    name: '1 de Paus',
    rule: 'Distribua 1 shot!',
    imgURL: require('../../assets/cards/ace_of_clubs.png'),
  },
  {
    id: 4,
    value: 1,
    suit: 'Copas',
    name: '1 de Copas',
    rule: 'Distribua 1 shot!',
    imgURL: require('../../assets/cards/ace_of_hearts.png'),
  },

  {
    id: 5,
    value: 2,
    suit: 'Ouros',
    name: '2 de Ouros',
    rule: 'Distribua 2 shots!',
    imgURL: require('../../assets/cards/2_of_diamonds.png'),
  },
  {
    id: 6,
    value: 2,
    suit: 'Copas',
    name: '2 de Copas',
    rule: 'Distribua 2 shots!',
    imgURL: require('../../assets/cards/2_of_hearts.png'),
  },
  {
    id: 7,
    value: 2,
    suit: 'Espadas',
    name: '2 de Espadas',
    rule: 'Distribua 2 shots!',
    imgURL: require('../../assets/cards/2_of_spades.png'),
  },
  {
    id: 8,
    value: 2,
    suit: 'Paus',
    name: '2 de Paus',
    rule: 'Distribua 2 shots!',
    imgURL: require('../../assets/cards/2_of_clubs.png'),
  },

  {
    id: 9,
    value: 3,
    suit: 'Ouros',
    name: '3 de Ouros',
    rule: 'Distribua 3 shots',
    imgURL: require('../../assets/cards/3_of_diamonds.png'),
  },
  {
    id: 10,
    value: 3,
    suit: 'Espadas',
    name: '3 de Espadas',
    rule: 'Distribua 3 shots',
    imgURL: require('../../assets/cards/3_of_spades.png'),
  },
  {
    id: 11,
    value: 3,
    suit: 'Copas',
    name: '3 de Copas',
    rule: 'Distribua 3 shots',
    imgURL: require('../../assets/cards/3_of_hearts.png'),
  },
  {
    id: 12,
    value: 3,
    suit: 'Paus',
    name: '3 de Paus',
    rule: 'Distribua 3 shots',
    imgURL: require('../../assets/cards/3_of_clubs.png'),
  },

  {
    id: 13,
    value: 4,
    suit: 'Ouros',
    name: '4 de Ouros',
    rule: 'Jogo: Eu nunca',
    imgURL: require('../../assets/cards/4_of_diamonds.png'),
  },
  {
    id: 14,
    value: 4,
    suit: 'Espadas',
    name: '4 de Espadas',
    rule: 'Jogo: Eu nunca',
    imgURL: require('../../assets/cards/4_of_spades.png'),
  },
  {
    id: 15,
    value: 4,
    suit: 'Copas',
    name: '4 de Copas',
    rule: 'Jogo: Eu nunca',
    imgURL: require('../../assets/cards/4_of_hearts.png'),
  },
  {
    id: 16,
    value: 4,
    suit: 'Paus',
    name: '4 de Paus',
    rule: 'Jogo: Eu nunca',
    imgURL: require('../../assets/cards/4_of_clubs.png'),
  },

  {
    id: 17,
    value: 5,
    suit: 'Ouros',
    name: '5 de Ouros',
    rule: 'Jogo: C ou S',
    imgURL: require('../../assets/cards/5_of_diamonds.png'),
  },
  {
    id: 18,
    value: 5,
    suit: 'Espadas',
    name: '5 de Espadas',
    rule: 'Jogo: C ou S',
    imgURL: require('../../assets/cards/5_of_spades.png'),
  },
  {
    id: 19,
    value: 5,
    suit: 'Copas',
    name: '5 de Copas',
    rule: 'Jogo: C ou S',
    imgURL: require('../../assets/cards/5_of_hearts.png'),
  },
  {
    id: 20,
    value: 5,
    suit: 'Paus',
    name: '5 de Paus',
    rule: 'Jogo: C ou S',
    imgURL: require('../../assets/cards/5_of_clubs.png'),
  },

  {
    id: 21,
    value: 6,
    suit: 'Ouros',
    name: '6 de Ouros',
    rule: 'Passe para o banheiro',
    imgURL: require('../../assets/cards/6_of_diamonds.png'),
  },
  {
    id: 22,
    value: 6,
    suit: 'Espadas',
    name: '6 de Espadas',
    rule: 'Passe para o banheiro',
    imgURL: require('../../assets/cards/6_of_spades.png'),
  },
  {
    id: 23,
    value: 6,
    suit: 'Copas',
    name: '6 de Copas',
    rule: 'Passe para o banheiro',
    imgURL: require('../../assets/cards/6_of_hearts.png'),
  },
  {
    id: 24,
    value: 6,
    suit: 'Paus',
    name: '6 de Paus',
    rule: 'Passe para o banheiro',
    imgURL: require('../../assets/cards/6_of_clubs.png'),
  },

  {
    id: 25,
    value: 7,
    suit: 'Copas',
    name: '7 de Copas',
    rule: 'Jogo: Pi',
    imgURL: require('../../assets/cards/7_of_hearts.png'),
  },
  {
    id: 26,
    value: 7,
    suit: 'Paus',
    name: '7 de Paus',
    rule: 'Jogo: Pi',
    imgURL: require('../../assets/cards/7_of_clubs.png'),
  },
  {
    id: 27,
    value: 7,
    suit: 'Espadas',
    name: '7 de Espadas',
    rule: 'Jogo: Pi',
    imgURL: require('../../assets/cards/7_of_spades.png'),
  },
  {
    id: 28,
    value: 7,
    suit: 'Ouros',
    name: '7 de Ouros',
    rule: 'Jogo: Pi',
    imgURL: require('../../assets/cards/7_of_diamonds.png'),
  },

  {
    id: 29,
    value: 8,
    suit: 'Ouros',
    name: '8 de Ouros',
    rule: 'Invente uma regra',
    imgURL: require('../../assets/cards/8_of_diamonds.png'),
  },
  {
    id: 30,
    value: 8,
    suit: 'Espadas',
    name: '8 de Espadas',
    rule: 'Invente uma regra',
    imgURL: require('../../assets/cards/8_of_spades.png'),
  },
  {
    id: 31,
    value: 8,
    suit: 'Copas',
    name: '8 de Copas',
    rule: 'Invente uma regra',
    imgURL: require('../../assets/cards/8_of_hearts.png'),
  },
  {
    id: 32,
    value: 8,
    suit: 'Paus',
    name: '8 de Paus',
    rule: 'Invente uma regra',
    imgURL: require('../../assets/cards/8_of_clubs.png'),
  },

  {
    id: 33,
    value: 9,
    suit: 'Copas',
    name: '9 de Copas',
    rule: 'Jogo: Dedinho',
    imgURL: require('../../assets/cards/9_of_hearts.png'),
  },
  {
    id: 34,
    value: 9,
    suit: 'Paus',
    name: '9 de Paus',
    rule: 'Jogo: Dedinho',
    imgURL: require('../../assets/cards/9_of_clubs.png'),
  },
  {
    id: 35,
    value: 9,
    suit: 'Espadas',
    name: '9 de Espadas',
    rule: 'Jogo: Dedinho',
    imgURL: require('../../assets/cards/9_of_spades.png'),
  },
  {
    id: 36,
    value: 9,
    suit: 'Ouros',
    name: '9 de Ouros',
    rule: 'Jogo: Dedinho',
    imgURL: require('../../assets/cards/9_of_diamonds.png'),
  },

  {
    id: 37,
    value: 10,
    suit: 'Ouros',
    name: '10 de Ouros',
    rule: 'Palavra Proibida',
    imgURL: require('../../assets/cards/10_of_diamonds.png'),
  },
  {
    id: 38,
    value: 10,
    suit: 'Espadas',
    name: '10 de Espadas',
    rule: 'Palavra Proibida',
    imgURL: require('../../assets/cards/10_of_spades.png'),
  },
  {
    id: 39,
    value: 10,
    suit: 'Copas',
    name: '10 de Copas',
    rule: 'Palavra Proibida',
    imgURL: require('../../assets/cards/10_of_hearts.png'),
  },
  {
    id: 40,
    value: 10,
    suit: 'Paus',
    name: '10 de Paus',
    rule: 'Palavra Proibida',
    imgURL: require('../../assets/cards/10_of_clubs.png'),
  },

  {
    id: 41,
    value: 11,
    suit: 'Ouros',
    name: '11 de Ouros',
    rule: 'Homens bebem',
    imgURL: require('../../assets/cards/jack_of_diamonds.png'),
  },
  {
    id: 42,
    value: 11,
    suit: 'Espadas',
    name: '11 de Espadas',
    rule: 'Homens bebem',
    imgURL: require('../../assets/cards/jack_of_spades.png'),
  },
  {
    id: 43,
    value: 11,
    suit: 'Copas',
    name: '11 de Copas',
    rule: 'Homens bebem',
    imgURL: require('../../assets/cards/jack_of_hearts.png'),
  },
  {
    id: 44,
    value: 11,
    suit: 'Paus',
    name: '11 de Paus',
    rule: 'Homens bebem',
    imgURL: require('../../assets/cards/jack_of_clubs.png'),
  },

  {
    id: 45,
    value: 12,
    suit: 'Ouros',
    name: '12 de Ouros',
    rule: 'Mulheres bebem',
    imgURL: require('../../assets/cards/queen_of_diamonds.png'),
  },
  {
    id: 46,
    value: 12,
    suit: 'Espadas',
    name: '12 de Espadas',
    rule: 'Mulheres bebem',
    imgURL: require('../../assets/cards/queen_of_spades.png'),
  },
  {
    id: 47,
    value: 12,
    suit: 'Copas',
    name: '12 de Copas',
    rule: 'Mulheres bebem',
    imgURL: require('../../assets/cards/queen_of_hearts.png'),
  },
  {
    id: 48,
    value: 12,
    suit: 'Paus',
    name: '12 de Paus',
    rule: 'Mulheres bebem',
    imgURL: require('../../assets/cards/queen_of_clubs.png'),
  },

  {
    id: 49,
    value: 13,
    suit: 'Ouros',
    name: '13 de Ouros',
    rule: 'Todos os jogadores bebem',
    imgURL: require('../../assets/cards/queen_of_diamonds.png'),
  },
  {
    id: 50,
    value: 13,
    suit: 'Espadas',
    name: '13 de Espadas',
    rule: 'Todos os jogadores bebem',
    imgURL: require('../../assets/cards/queen_of_spades.png'),
  },
  {
    id: 51,
    value: 13,
    suit: 'Copas',
    name: '13 de Copas',
    rule: 'Todos os jogadores bebem',
    imgURL: require('../../assets/cards/queen_of_hearts.png'),
  },
  {
    id: 52,
    value: 13,
    suit: 'Paus',
    name: '13 de Paus',
    rule: 'Todos os jogadores bebem',
    imgURL: require('../../assets/cards/queen_of_clubs.png'),
  },
];

export class card {
  id: number;
  value: number;
  suit: string;
  name: string;
  rule: string;
  imgURL: string;
}
